name: foodistan
description: A new Flutter application. Foodistaan.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  bloc: ^8.0.1
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.0
  country_code_picker: ^2.0.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.3
  firebase_auth: ^3.1.3
  firebase_core: ^1.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_polyline_points: ^1.0.0
  flutter_rating_bar: ^4.0.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^0.23.0+1
  fluttertoast: ^8.0.8
  font_awesome_flutter: ^9.2.0
  geocoding: ^2.0.0
  geolocator: ^7.7.0
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.1.0
  intl_phone_field: ^2.1.0
  location: ^4.3.0
  lottie: ^1.2.1
  modal_bottom_sheet: ^2.0.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  otp_text_field: ^1.1.1
  page_transition: ^2.0.4
  persistent_bottom_nav_bar: ^4.0.2
  pin_code_fields: ^7.3.0
  pinput: ^1.2.2
  provider: ^6.0.2
  qr_code_scanner: ^0.6.1
  razorpay_flutter: ^1.2.7
  readmore: ^2.1.0
  rflutter_alert: ^2.0.4
  shared_preferences: ^2.0.11
  sizer: ^2.0.15
  solid_bottom_sheet: ^0.1.10
  titled_navigation_bar: ^5.0.0-nullsafety.0
  uuid: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - Images/
